#!/bin/bash

print_games_list() {
python - $1 <<EOF
import json
import sys

with open(sys.argv[1], 'r') as f:
	apps = json.load(f)

for game in apps['applist']['apps']:
	print(str(game['appid']).ljust(13), '=> ', game['name'])
EOF
}

app_id=$(print_games_list <( curl -s "https://api.steampowered.com/ISteamApps/GetAppList/v2/" ) | fzf | cut --delimiter ' ' --field 1)

wait4 -s "$app_id"

